include/RBELib/SetServo.h File Reference
This file allows for using the SerSevo function to move the conveyor and gripper.
Macros
#define CLK 18432000
Functions
void setServo (int Pin, int Value)
Set a servo to a desired value.
void initAltCom (unsigned long baudrate)
Used to initialize UART0 for communication with the coprocessor. It should never be called manually.
void setCharDebug (char byteToSend)
Used to put a char on UART0. It should never be called manually and is used by printf().
void coPrintf (char *str)
String to send to the coprocessor via UART0.
Detailed Description
This file allows for using the SerSevo function to move the conveyor and gripper.
Author
cwrus
Date
Jun 28, 2012
Author
Eric Willcox
Date
July 9, 2014
Definition in file SetServo.h.
Macro Definition Documentation
#define CLK 18432000
Definition at line 16 of file SetServo.h.
Referenced by initAltCom().
Function Documentation
void coPrintf (char * str)
String to send to the coprocessor via UART0.
Parameters
*str String to send.
Definition at line 71 of file SetServo.c.
References setCharDebug().
Referenced by setServo().
void initAltCom (unsigned long baudrate)
Used to initialize UART0 for communication with the coprocessor. It should never be called manually.
Parameters
baudrate Baud rate of the communication line in bps.
Definition at line 28 of file SetServo.c.
References CLK.
Referenced by initRBELib().
void setCharDebug (char byteToSend)
Used to put a char on UART0. It should never be called manually and is used by printf().
Parameters
byteToSend Character to send
Definition at line 57 of file SetServo.c.
Referenced by coPrintf().
void setServo (int Pin, int Value)
Set a servo to a desired value.
Parameters
Pin Pin number.
Value Value to set the pin to.
Definition at line 17 of file SetServo.c.
References coPrintf().